const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={data:null,activeStimulus:null,world:{x:500,y:300,vx:0,vy:0,food:0,energy:100,start:performance.now()},evo:store.get('mcp-evo',{generation:1,speed:1,sense:1,survival:50}),builder:store.get('mcp-builder',[])};

$('#menuBtn')?.addEventListener('click',()=>$('#nav').classList.toggle('open'));
$$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open')));

async function loadData(){state.data=await fetch('./data/flybrain-demo.json').then(r=>r.json());drawBrain();drawHero();drawSim();}
function fit(canvas){const dpr=Math.max(1,Math.min(2,devicePixelRatio||1));const rect=canvas.getBoundingClientRect();if(canvas.width!==Math.floor(rect.width*dpr)||canvas.height!==Math.floor((rect.width*(canvas.dataset.ratio||.62))*dpr)){canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.width*(canvas.dataset.ratio||.62)*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:rect.width,h:rect.width*(canvas.dataset.ratio||.62)}}
function color(group){return({visual:'#7db7ff',olfactory:'#ffd166',sensory:'#ff9f80',processing:'#b89cff',escape:'#ff738a',motor:'#78f5c7'})[group]||'#fff'}
function drawNetwork(canvas,opts={}){if(!state.data)return;const {ctx,w,h}=fit(canvas);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d111a';ctx.fillRect(0,0,w,h);const nodes=state.data.nodes.map(n=>({...n,px:n.x*w,py:n.y*h}));const map=Object.fromEntries(nodes.map(n=>[n.id,n]));for(const [a,b] of state.data.edges){const A=map[a],B=map[b];ctx.strokeStyle='rgba(166,174,196,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(A.px,A.py);ctx.lineTo(B.px,B.py);ctx.stroke();}
const active=opts.active||new Set();nodes.forEach(n=>{const is=active.has(n.id);ctx.beginPath();ctx.arc(n.px,n.py,is?13:9,0,Math.PI*2);ctx.fillStyle=is?'#fff':color(n.group);ctx.shadowColor=is?color(n.group):'transparent';ctx.shadowBlur=is?28:0;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#dfe5f5';ctx.font='12px system-ui';ctx.fillText(n.label,n.px+15,n.py+4)});return{nodes,w,h}}
function drawBrain(){const canvas=$('#brainCanvas');if(!canvas)return;canvas.dataset.ratio=.62;drawNetwork(canvas);canvas.onclick=(e)=>{const rect=canvas.getBoundingClientRect();const x=e.clientX-rect.left,y=e.clientY-rect.top;const res=drawNetwork(canvas);let best=null,bd=999;for(const n of res.nodes){const d=Math.hypot(n.px-x,n.py-y);if(d<bd){best=n;bd=d}}if(best&&bd<35){$('#nodeTitle').textContent=best.label;$('#nodeDescription').textContent=best.description;const ins=state.data.edges.filter(([a,b])=>a===best.id||b===best.id).length;$('#nodeMeta').innerHTML=`<dt>Grupo</dt><dd>${best.group}</dd><dt>Conexões</dt><dd>${ins}</dd><dt>ID</dt><dd>${best.id}</dd>`}}}
function drawHero(){const canvas=$('#heroCanvas');if(!canvas)return;canvas.dataset.ratio=.72;let t=0;const loop=()=>{t+=.03;const active=new Set(state.data.nodes.filter((_,i)=>Math.sin(t+i*.85)>0.72).map(n=>n.id));drawNetwork(canvas,{active});requestAnimationFrame(loop)};loop()}
const paths={light:['vision','integrator','escape','motorL'],food:['smell','integrator','forage','motorR'],touch:['touch','escape','motorL','motorR'],danger:['vision','integrator','escape','motorL','motorR']};
function drawSim(){const c=$('#simCanvas');if(!c||!state.data)return;c.dataset.ratio=.52;drawNetwork(c)}
$$('.stimulus').forEach(btn=>btn.onclick=()=>{state.activeStimulus=btn.dataset.stimulus;$$('.stimulus').forEach(b=>b.classList.toggle('active',b===btn));const seq=paths[state.activeStimulus];let i=0;$('#simStatus').textContent='Propagando sinal localmente…';const timer=setInterval(()=>{drawNetwork($('#simCanvas'),{active:new Set(seq.slice(0,i+1))});i++;if(i>=seq.length){clearInterval(timer);$('#simStatus').textContent=`Resposta demonstrativa concluída: ${seq.join(' → ')}`}},420)});

const worldCanvas=$('#worldCanvas');let foods=[],threats=[];function resetWorld(){state.world={x:500,y:300,vx:0,vy:0,food:0,energy:100,start:performance.now()};foods=Array.from({length:7},()=>({x:80+Math.random()*840,y:80+Math.random()*440}));threats=Array.from({length:3},()=>({x:120+Math.random()*760,y:120+Math.random()*360,vx:(Math.random()-.5)*1.3,vy:(Math.random()-.5)*1.3}))}resetWorld();$('#resetWorld')?.addEventListener('click',resetWorld);
function worldLoop(){if(worldCanvas){worldCanvas.dataset.ratio=.6;const {ctx,w,h}=fit(worldCanvas);ctx.fillStyle='#0e1520';ctx.fillRect(0,0,w,h);const sx=w/1000,sy=h/600;const fly=state.world;let target=foods[0];for(const f of foods)if(Math.hypot(f.x-fly.x,f.y-fly.y)<Math.hypot(target.x-fly.x,target.y-fly.y))target=f;let ax=0,ay=0;if(target){const d=Math.max(1,Math.hypot(target.x-fly.x,target.y-fly.y));ax+=(target.x-fly.x)/d*.045;ay+=(target.y-fly.y)/d*.045}for(const t of threats){const d=Math.hypot(t.x-fly.x,t.y-fly.y);if(d<170){ax+=(fly.x-t.x)/Math.max(d,1)*.18;ay+=(fly.y-t.y)/Math.max(d,1)*.18}t.x+=t.vx;t.y+=t.vy;if(t.x<20||t.x>980)t.vx*=-1;if(t.y<20||t.y>580)t.vy*=-1}
fly.vx=(fly.vx+ax)*.985;fly.vy=(fly.vy+ay)*.985;const speed=Math.hypot(fly.vx,fly.vy);if(speed>3.4){fly.vx*=3.4/speed;fly.vy*=3.4/speed}fly.x=Math.max(20,Math.min(980,fly.x+fly.vx));fly.y=Math.max(20,Math.min(580,fly.y+fly.vy));fly.energy=Math.max(0,fly.energy-.006);
foods=foods.filter(f=>{if(Math.hypot(f.x-fly.x,f.y-fly.y)<22){fly.food++;fly.energy=Math.min(100,fly.energy+18);return false}return true});if(foods.length<5)foods.push({x:80+Math.random()*840,y:80+Math.random()*440});
foods.forEach(f=>{ctx.fillStyle='#ffd166';ctx.beginPath();ctx.arc(f.x*sx,f.y*sy,8,0,Math.PI*2);ctx.fill()});threats.forEach(t=>{ctx.fillStyle='#ff6b7f';ctx.beginPath();ctx.arc(t.x*sx,t.y*sy,13,0,Math.PI*2);ctx.fill()});ctx.font='28px sans-serif';ctx.fillText('🪰',fly.x*sx-14,fly.y*sy+10);$('#foodCount').textContent=`Comidas: ${fly.food}`;$('#ageCount').textContent=`Tempo: ${Math.floor((performance.now()-fly.start)/1000)}s`;$('#energyCount').textContent=`Energia: ${Math.round(fly.energy)}`;}requestAnimationFrame(worldLoop)}worldLoop();

$('#labTest')?.addEventListener('click',()=>{const on=Object.fromEntries($$('[data-lab]').map(x=>[x.dataset.lab,x.checked]));let msgs=[];if(!on.visual)msgs.push('resposta visual indisponível');if(!on.olfactory)msgs.push('busca por odor prejudicada');if(!on.escape)msgs.push('fuga reduzida');if(!on.motor)msgs.push('sem saída motora');$('#labResult').textContent=msgs.length?`Teste demonstrativo: ${msgs.join('; ')}.`:'Todos os circuitos selecionados responderam normalmente nesta simulação simplificada.'});

function renderEvo(){const e=state.evo;$('#generation').textContent=e.generation;$('#avgSpeed').textContent=e.speed.toFixed(2);$('#avgSense').textContent=e.sense.toFixed(2);$('#survival').textContent=`${Math.round(e.survival)}%`;const c=$('#evoCanvas');if(!c)return;c.dataset.ratio=.42;const {ctx,w,h}=fit(c);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0d111a';ctx.fillRect(0,0,w,h);for(let i=0;i<36;i++){const x=35+(i%12)*(w-70)/11,y=50+Math.floor(i/12)*(h-100)/2;ctx.font=`${20+Math.random()*10}px sans-serif`;ctx.globalAlpha=.45+Math.random()*.55;ctx.fillText('🪰',x,y)}ctx.globalAlpha=1}renderEvo();$('#nextGeneration')?.addEventListener('click',()=>{state.evo.generation++;state.evo.speed=Math.max(.5,state.evo.speed+(Math.random()-.35)*.08);state.evo.sense=Math.max(.5,state.evo.sense+(Math.random()-.35)*.07);state.evo.survival=Math.max(10,Math.min(95,state.evo.survival+(Math.random()-.42)*8));store.set('mcp-evo',state.evo);renderEvo()});

function renderBuilder(){const b=$('#builderBoard');if(!b)return;b.innerHTML=state.builder.length?'':'<p class="muted">Adicione componentes. Eles serão conectados na ordem em que forem criados.</p>';state.builder.forEach((n,i)=>{const el=document.createElement('div');el.className='node-block';el.innerHTML=`<strong>${n.type==='sensor'?'📡 Sensor':n.type==='neuron'?'🧠 Neurônio':'⚙️ Motor'}</strong><div class="muted">#${i+1}</div>`;b.appendChild(el)});store.set('mcp-builder',state.builder)}renderBuilder();$$('[data-builder]').forEach(btn=>btn.onclick=()=>{state.builder.push({type:btn.dataset.builder});renderBuilder()});$('#clearBuilder')?.addEventListener('click',()=>{state.builder=[];renderBuilder()});

$$('[data-answer]').forEach(btn=>btn.onclick=()=>{$('#quizFeedback').textContent=btn.dataset.answer==='correct'?'✅ Correto! Nesta demonstração, o sensor visual recebe primeiro o estímulo de luz.':'❌ Tente novamente.'});

window.addEventListener('resize',()=>{drawBrain();drawSim();renderEvo()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
loadData().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div style="position:fixed;bottom:10px;left:10px;right:10px;background:#491f28;padding:12px;border-radius:12px">Não foi possível carregar o dataset local. Use um servidor HTTP/Cloudflare, não abra o HTML diretamente como arquivo.</div>')});